// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXghe9OwufqmrRg-L1WvEtOnEiMsCiuQ',
    appId: '1:511388205844:web:2308c0ce37721a841df801',
    messagingSenderId: '511388205844',
    projectId: 'campus-faadf',
    authDomain: 'campus-faadf.firebaseapp.com',
    storageBucket: 'campus-faadf.appspot.com',
    measurementId: 'G-NSV6571K9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDEdO9vUEHTw2RWFXT9eP29tXwNgIX9U',
    appId: '1:511388205844:android:6bb572aff2eac9181df801',
    messagingSenderId: '511388205844',
    projectId: 'campus-faadf',
    storageBucket: 'campus-faadf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxkJVR_LIs-xhm5FiyA4JZ9TmN8VrNbQ',
    appId: '1:511388205844:ios:a8d892d9621015591df801',
    messagingSenderId: '511388205844',
    projectId: 'campus-faadf',
    storageBucket: 'campus-faadf.appspot.com',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxkJVR_LIs-xhm5FiyA4JZ9TmN8VrNbQ',
    appId: '1:511388205844:ios:d3bbe09efc6c98cf1df801',
    messagingSenderId: '511388205844',
    projectId: 'campus-faadf',
    storageBucket: 'campus-faadf.appspot.com',
    iosBundleId: 'com.example.collegeapp.RunnerTests',
  );
}
